# ?????? ???? ?????????? ?? 8081, ???? 8080 ?????
server.port=8081

# ????????? ??????????? ? PostgreSQL
# ?????? ????????: ???? 5433, ???? lms_db
spring.datasource.url=jdbc:postgresql://localhost:5433/lms_db
spring.datasource.username=postgres
spring.datasource.password=1151
spring.datasource.driver-class-name=org.postgresql.Driver

# ????????? JPA / Hibernate
# update ? ????????????? ??????? ??????? ??? ?????? ???????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ????????? H2 ???????, ??? ??? ?? ??????? ?? ???????? ??
spring.h2.console.enabled=false